### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ian B",
  "email": "ian@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###USER INDEX
GET http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNzA1MjR9.lKr9BlAz5FQIGfivN2Ex3jovCd5mgesUwRRrgcHEMbc
Content-Type: application/json